# Generated by Django 5.2.4 on 2025-07-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sequence', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('valeur_actuelle', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('nom_sequence', 'annee')},
            },
        ),
    ]
