# Generated by Django 5.2.4 on 2025-07-23 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conformiterapportdetail',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personneladministratif'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='est_eligible_soumission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='procesverbal',
            name='date_finalisation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportetudiant',
            name='commentaires_conformite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapportetudiant',
            name='note_explicative_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionvalidation',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='sessions_commission', to='core.enseignant'),
        ),
        migrations.AddField(
            model_name='sessionvalidation',
            name='nombre_votants_requis',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stage',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions_delegues', models.JSONField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_active', models.BooleanField(default=True)),
                ('delegant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_faites', to=settings.AUTH_USER_MODEL)),
                ('delegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('type_notification', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_action', models.CharField(blank=True, max_length=255, null=True)),
                ('est_archivee', models.BooleanField(default=False)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('RECLA_OUVERTE', 'Ouverte'), ('RECLA_EN_COURS', 'En cours de traitement'), ('RECLA_RESOLUE', 'Résolue'), ('RECLA_CLOTUREE', 'Clôturée')], default='RECLA_OUVERTE', max_length=50)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True, null=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_assignees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='core.etudiant')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOfficiel',
            fields=[
                ('id_document', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_document', models.CharField(max_length=100)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('est_officiel', models.BooleanField(default=True)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.anneeacademique')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.personneladministratif')),
            ],
            options={
                'ordering': ['-date_generation'],
                'unique_together': {('etudiant', 'type_document', 'annee_academique', 'version')},
            },
        ),
    ]
