"""
Django settings for config2 project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []




# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
]

# config/settings.py

JAZZMIN_SETTINGS = {
    # Thème et Titres
    "site_title": "GMS Admin",
    "site_header": "GestionMySoutenance",
    "site_brand": "GMS",
    "welcome_sign": "Bienvenue sur l'administration de GestionMySoutenance",
    "copyright": "GestionMySoutenance Ltd",
    "default_theme": "darkly",

    # Affichage
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Icônes pour les applications et modèles
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Etudiant": "fas fa-user-graduate",
        "core.Enseignant": "fas fa-chalkboard-teacher",
        "core.PersonnelAdministratif": "fas fa-user-tie",
        "core.AnneeAcademique": "fas fa-calendar-alt",
        "core.NiveauEtude": "fas fa-layer-group",
        "core.Specialite": "fas fa-star",
        "core.RapportEtudiant": "fas fa-file-alt",
        "core.SessionValidation": "fas fa-gavel",
        "core.Inscription": "fas fa-id-card",
        "core.Stage": "fas fa-building",
        "core.Penalite": "fas fa-exclamation-triangle",
        "core.CritereConformite": "fas fa-check-double",
    },

    # Ordre et regroupement du menu
    "order_with_respect_to": [
        # Groupe 1: Accès & Profils
        "auth",
        "core.Etudiant",
        "core.Enseignant",
        "core.PersonnelAdministratif",

        # Groupe 2: Structure Académique
        "core.AnneeAcademique",
        "core.NiveauEtude",
        "core.Specialite",
        "core.Ue",
        "core.Ecue",
        "core.Entreprise",

        # Groupe 3: Workflow de Soutenance
        "core.RapportEtudiant",
        "core.SessionValidation",
        "core.ProcesVerbal",

        # Groupe 4: Gestion Administrative
        "core.Inscription",
        "core.Stage",
        "core.Penalite",
        "core.Note",

        # Groupe 5: Paramètres
        "core.CritereConformite",
        "core.Grade",
        "core.Fonction",
    ],

    # Liens personnalisés pour créer les "dossiers" du menu
    "custom_links": {
        "core": [{
            "name": "Faire un lien",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["auth.view_user"]
        }]
    }
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
